FROM openjdk:11-jre-slim
WORKDIR /helidon

# Copy the binary built in the 1st stage
COPY target/acmeair-flightservice-java.jar ./helidon.jar
COPY target/libs ./libs

CMD ["java","-jar", "helidon.jar"]

EXPOSE 9080
